language: scala

scala:
   - 2.12.7

jdk:
 - oraclejdk8
 - oraclejdk9
 - openjdk11

install:
   - . $HOME/.nvm/nvm.sh
   - nvm install stable
   - nvm use stable
   - npm install
   - npm install jsdom

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt